-- create
CREATE TABLE USER (
  UID VARCHAR(40) NOT NULL,
  USER_PASSWORD TEXT NOT NULL,
  CN VARCHAR(50) NOT NULL,
  PRIMARY KEY (`UID`)
);

-- insert
INSERT INTO USER (UID, USER_PASSWORD, CN) VALUES ('test', HASH('SHA256', STRINGTOUTF8('test'), 1), '테스트');
